version: 1
disable_existing_loggers: false
formatters:
  standard:
    format: "[%(asctime)s] %(levelname)s in %(module)s: %(message)s"
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: standard
    stream: ext://sys.stdout
  file:
    class: logging.handlers.TimedRotatingFileHandler
    level: INFO
    formatter: standard
    filename: log/app.log
    when: midnight
    interval: 1
    backupCount: 31
    encoding: utf8
root:
  level: INFO
  handlers: [console, file]
loggers:
  uvicorn:
    handlers: [console, file]
    level: INFO
    propagate: false
  uvicorn.error:
    handlers: [console, file]
    level: INFO
    propagate: false
  uvicorn.access:
    handlers: [console, file]
    level: INFO
    propagate: false
